### ISSUE TITLE
Context menu "Apply to Prefab" / "Apply as override of <prfab variant>" doesn't show in the context menu if custom script assigned to the prefab

### ISSUE THREAD

**Issue by tettogreen** [SisusCo/Power-Inspector-Public#11]
Unity Version: 2018.4.11.f1
OS: Windows 

**Steps:**
1. Add any custom written component to the prefab variant
2. Right click the added component

**Result:**
Context menu has no "Apply to Prefab" / "Apply as override of <prfab variant>" options

**Expected Result:**
Context menu should have "Apply to Prefab" / "Apply as override of <prfab variant>" options

![image](https://user-images.githubusercontent.com/4964268/72211786-c96af900-34d9-11ea-9303-098f4271c138.png)

**Comment by timo-sisus** [comment]
Context menu items for applying and reverting changes were added to all components that belong to a prefab instance.

**Comment by tettogreen** [comment]
Thanks!
