### ISSUE TITLE
Multiple array elements assignment doesn't work

### ISSUE THREAD

**Issue by tettogreen** [SisusCo/Power-Inspector-Public#12]
Unity Version: 2018.4.11.f1
OS: Windows 

**Steps:**
1. Add any custom written component with serialized array or list of e.g. scriptable objects
2. In porject hierarchy select multiple instances of appropriate scriptable object
3. Drag and drop them onto array name in the inspector

**Result:**
Nothing happens

**Expected Result:**
Values should be added to the array. **This feature is standard Unity feature**

**Comment by timo-sisus** [comment]
Implemented ability to add one or more Objects to an Object collection by dragging them onto the prefix label of the collection.

**Comment by tettogreen** [comment]
Thanks!
