### ISSUE TITLE
infinite loop (hang unity) when Debug+ inspecting a new Input Control

### ISSUE THREAD

**Issue by jasonswearingen** [SisusCo/Power-Inspector-Public#17]
I just bought your inspector, and it seems to work on normal unity objects.

I tried using it on the new InputController, and it's not working.  seems to be due to an infinite loop (unity crashes)   attaching a debugger shows that the power inspector code spins parsing properties.

i attached a project to repro with. [edit: downloaded and removed]

repo steps:
1. open in unity 2019.3 and after it all loads, open up the Assets/Scenes/SampleScene
1. using the powerInspector, click on ```dwarf_hero``` in the hiearchy, 
1. for the ```Player (Script)``` component, click the ```Debug+``` option
1. expand and then try to collapse the ```Plyr Ctrls``` property.   This causes an infinite loop in power-inspector.

**Comment by timo-sisus** [comment]
This should be fixed in next version.
