### ISSUE TITLE
Multi select dropdown parity mismatching

### ISSUE THREAD

**Issue by Cronoo** [SisusCo/Power-Inspector-Public#19]
Unity 2019.3.4f1
Power Inspector 1.3.3
Windows 10 Pro Build 10.0.18362

The multi selections drop down menu parity seems to be mismatching between the default inspector and power inspector.

![2020-03-11_14-22-11](https://user-images.githubusercontent.com/6293039/76467060-fe92ab00-63a5-11ea-91d8-3d35d0f95fca.jpg)

It seems to select stuff 3 slots lower than the default inspector and vice versa ![Screenshot 2020-03-11 14 42 12](https://user-images.githubusercontent.com/6293039/76467361-b2943600-63a6-11ea-8d1a-5b1ca0da8d60.png)

**Comment by timo-sisus** [comment]
Thanks for the report! This will be fixed in update 1.3.4.
