### ISSUE TITLE
Unity crashes when copying/pasting an AnimationCurve content into another object through PowerInspector

### ISSUE THREAD

**Issue by Masklin** [SisusCo/Power-Inspector-Public#22]
On a fresh project, I import PowerInspector and create a script with just an AnimationCurve field. I add this script to two simple game objects in a scene (boxes or spheres for example) and edit the curve in one of the objects. Then, through a PowerInspector window I select the AnimationCurve, copy it and paste it in the other object. Unity crashes.

**Comment by timo-sisus** [comment]
Copy-paste support will be coming to AnimationCurves in the next update via the new AnimationCurveJsonConverter.
