### ISSUE TITLE
Selecting a new Material in the material list updates the selected material just once.

### ISSUE THREAD

**Issue by ArkyonVeil** [SisusCo/Power-Inspector-Public#24]
Noted an issue with the Power Inspector.

-When selecting a new material to apply to a sprite from the material list, the first selection works. But all other selections do nothing, even double clicking reveals that the only selection accepted is the first one.

Attached is a clip of the bug in action.

Using version 1.5.0 of power Inspector
Using Unity 2019.4.8f1

-Dev, pls fix.
[PowerInspectorMaterialBug.zip](https://github.com/SisusCo/Power-Inspector/files/5469694/PowerInspectorMaterialBug.zip)

**Comment by timo-sisus** [comment]
Thanks for reporting this issue! A fix for this will be included in the next version of Power Inspector.
