### ISSUE TITLE
"SerializedObject target has been destroyed" console spam on exiting Play Mode

### ISSUE THREAD

**Issue by ArkyonVeil** [SisusCo/Power-Inspector-Public#26]
Sometimes when exiting play mode, (SerializedObject target has been destroyed) is spammed to the console several times per second until the object is deselected.

Error trace below: 

SerializedObject target has been destroyed.
UnityEditor.MeshRendererEditor:OnInspectorGUI()
Sisus.CustomEditorBaseDrawer`2:DrawOnInspectorGUI(Editor) (at Assets/Sisus/Power Inspector/Code/Editor/Drawers/UnityObject/CustomEditorBaseDrawer.cs:1062)
Sisus.CustomEditorBaseDrawer`2:OnInspectorGUI(Editor) (at Assets/Sisus/Power Inspector/Code/Editor/Drawers/UnityObject/CustomEditorBaseDrawer.cs:1012)
Sisus.CustomEditorBaseDrawer`2:DrawMembers(Rect) (at Assets/Sisus/Power Inspector/Code/Editor/Drawers/UnityObject/CustomEditorBaseDrawer.cs:880)
Sisus.CustomEditorBaseDrawer`2:DrawBody(Rect) (at Assets/Sisus/Power Inspector/Code/Editor/Drawers/UnityObject/CustomEditorBaseDrawer.cs:836)
Sisus.RendererDrawer:DrawBody(Rect) (at Assets/Sisus/Power Inspector/Code/Editor/Drawers/UnityObject/Component/CustomEditor/RendererDrawer.cs:28)
Sisus.CustomEditorBaseDrawer`2:Draw(Rect) (at Assets/Sisus/Power Inspector/Code/Editor/Drawers/UnityObject/CustomEditorBaseDrawer.cs:751)
Sisus.GameObjectDrawer:DrawBody(Rect) (at Assets/Sisus/Power Inspector/Code/Editor/Drawers/UnityObject/GameObject/GameObjectDrawer.cs:1877)
Sisus.GameObjectDrawer:Draw(Rect) (at Assets/Sisus/Power Inspector/Code/Editor/Drawers/UnityObject/GameObject/GameObjectDrawer.cs:1687)
Sisus.Inspector`2:DrawViewport() (at Assets/Sisus/Power Inspector/Code/Editor/Inspector/Core/Inspector.cs:1892)
Sisus.Inspector`2:DrawViewport(Rect) (at Assets/Sisus/Power Inspector/Code/Editor/Inspector/Core/Inspector.cs:1817)
Sisus.PowerInspector:OnGUI(Rect, Boolean) (at Assets/Sisus/Power Inspector/Code/Editor/Inspector/Power Inspector/PowerInspector.cs:139)
Sisus.InspectorDrawerWindow`2:OnGUI() (at Assets/Sisus/Power Inspector/Code/Editor/EditorWindow/InspectorDrawerWindow.cs:2195)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

On this specific instance it occured to a Meshrenderer but I've also seen it happen to a Line Renderer.
Doesn't seem to be causing any issue that I can see, but its rather distracting and worrysome.

-Dev, pretty pls fix.

**Comment by timo-sisus** [comment]
I was not yet able to completely get rid of this error even after trying several approaches. Since the error originates from an internal Unity Editor it might just be impossible for me to fix this.

However I added a workaround where the inspector's drawers are rebuilt at the first sign of this error, so at least the console shouldn't get endlessly spammed any longer when this occurs. An update with this fix has been submitted to the asset store for approval.
