### ISSUE TITLE
Errors on Import

### ISSUE THREAD

**Issue by jjolley** [SisusCo/Power-Inspector-Public#27]
Unity 2020.1

The following errors are present on input:

Assets\Sisus\Power Inspector\Code\Editor\Compatibility\OdinInspectorAttributeConverterProvider.cs(133,42): error CS1061: 'ShowIfAttribute' does not contain a definition for 'Condition' and no accessible extension method 'Condition' accepting a first argument of type 'ShowIfAttribute' could be found (are you missing a using directive or an assembly reference?)

Assets\Sisus\Power Inspector\Code\Editor\Compatibility\OdinInspectorAttributeConverterProvider.cs(140,48): error CS1061: 'DisableIfAttribute' does not contain a definition for 'Condition' and no accessible extension method 'Condition' accepting a first argument of type 'DisableIfAttribute' could be found (are you missing a using directive or an assembly reference?)

Assets\Sisus\Power Inspector\Code\Editor\Extensions\TypeExtensions.cs(498,30): error CS0104: 'AssemblyFlags' is an ambiguous reference between 'UnityEditor.Compilation.AssemblyFlags' and 'System.Reflection.AssemblyFlags'

Assets\Sisus\Power Inspector\Code\Editor\Extensions\TypeExtensions.cs(498,63): error CS0104: 'AssemblyFlags' is an ambiguous reference between 'UnityEditor.Compilation.AssemblyFlags' and 'System.Reflection.AssemblyFlags'

**Comment by timo-sisus** [comment]
Thanks for the reporting this!

An update adding support for the latest version of Odin has been submitted to the asset store for approval.

And although I was not able to reproduce the second set of errors for myself, I also added a new using directive for UnityEditor.Compilation.AssemblyFlags in TypeExtensions which in theory should make the those errors go away too.
