### ISSUE TITLE
XML Comment Tooltips omit attribute value strings for common attribute types

### ISSUE THREAD

**Issue by adreyer-tpci** [SisusCo/Power-Inspector-Public#34]
When a class, parameter, or type parameter reference is embedded in an XML header comment, the auto-generated XML tooltip that appears in PowerInspector omits the contents of the attribute value entirely. The absence of important inline class or method names present in these comments makes them impossible to understand without inspecting the source script.

For example, observe how the XML comment for `someScalerValue` appears in JetBrains Rider's Documentation panel:

![rider_xml_header_source](https://user-images.githubusercontent.com/114530261/192640204-aa8c70c7-b41b-4831-9af2-751e40837a28.png)

Versus how it appears in PowerInspector's tooltip window, where the "SomeUtilityClass" and "PrintScalerValue" strings are missing:

![powerinspector_xml_missing_string](https://user-images.githubusercontent.com/114530261/192639571-8f6fe2c3-62bc-48be-9810-c005dc7425d8.png)

This is the case for all XML attributes with embedded attribute values, including:
- `<see cref=...`
- `<seealso cref=...`
- `<exception cref=...`
- `<param name=...`
- `<paramref name=...`
- `<typeparam name=...`
- `<typeparamref name=...`

At least printing the contents of any `cref` or `name` attribute value would help considerably.

**Comment by timo-sisus** [comment]
The inner texts of the `cref` and `name` tags will be included in tooltip texts in Power Inspector version 1.6.6.

The new version has been submitted to the asset store for approval - which usually takes around a day or so.
